### ISSUE TITLE
Visualization?

### ISSUE THREAD

**Issue by youmustfight** [navahq/branches#8]
👋hey Nava!

Thanks for open-sourcing all this ❤️Upsolve has been using this for our screener and it's been delightful! We're aiming to use it for our main application at some point and had a quick question.

With your graphs, did you have automatically generating documentation or visualizations that could help internal teams inspect graphs/questions and give feedback?

For example, with our current setup, our customer success team gets feedback from users saying a question is confusing and then it's hard for our team to find that question and surrounding questions in thousands of lines of questionnaire logic. Our service as it works now requires them login as the user and step through the questionnaire page by page to sense where they were coming from. Curious if you had to solve that problem and how you went about it

Thanks again!!!

**Comment by sawyerh** [comment]
Whoa, very cool to hear y'all have been using this! 🎉 

We didn't get to the point of generating documentation or visualizations from our graph unfortunately, though that would definitely be cool. A similar'ish library that does do that is [XState](https://xstate.js.org/docs/), in case you want to check that out.
